### ISSUE TITLE
README refers non-existing `siteMeta` function

### ISSUE THREAD

**Issue by develop7** [ChrisPenner/slick-template#1]
https://github.com/ChrisPenner/slick-template/blob/d80ed255587b5c7c224f3e41327db5941dba24c3/README.md#L13

**Comment by ChrisPenner** [comment]
Thanks for pointing that out!

Whoops; really not sure how that ended up happening; I must have pushed the wrong branch or something. Let me know if you have any trouble with the new `Main.hs` 👍 

Should be fixed ✅
