### ISSUE TITLE
"Must set shakeLintInside"

### ISSUE THREAD

**Issue by mrkgnao** [ChrisPenner/slick-template#5]
Build fails with current `master` on my system unless `shakeLintInside = [<paths>]` (I simply used `["\\"]`) is set in the Shake options.

```
❯ ghc -V
The Glorious Glasgow Haskell Compilation System, version 8.8.2

❯ cabal -V
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library
```

**Comment by ChrisPenner** [comment]
Hey Soham!

Hrmm, I'm not seeing this when building with `stack build`; I also tried with cabal, but that crashes on building `semigroupoids` for some reason. I added some version bounds on latest master, can you try again?

Sorry It took me so long to get around to this 😓

**Comment by JonathanLorimer** [comment]
I got the same issue btw.
```
➜ ghc -V
The Glorious Glasgow Haskell Compilation System, version 8.6.3

➜ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

**Comment by ChrisPenner** [comment]
@JonathanLorimer You got this error when building with `stack build`? Did you alter the LTS or leave it as-is?

BTW for future reference `stack` doesn't use your system GHC, so that version number doesn't really matter 😄

**Comment by JonathanLorimer** [comment]
Yes, I got the error when using `stack build`. I left the LTS alone, it is `lts-14.22` and the ghc version is `v8.6.5`.

Adding `shakeLintInside = ["\\"]` fixed it for me too though.

**Comment by ChrisPenner** [comment]
Strange! I still can't reproduce it, but it doesn't do any harm to add it, so it's in there on master now. Thanks everyone!
