### ISSUE TITLE
Adding tags section like on ChrisPenner.ca

### ISSUE THREAD

**Issue by ghost** [ChrisPenner/slick-template#6]
Hi there,

I just started playing with slick and this template (it's great, thanks!). I was just wondering how you managed to get the tags links (under All Posts) on your blog to work? is that functionality built-in to slick and/or this template or is that some custom magic that you built?

**Comment by ChrisPenner** [comment]
Hello!

This is one of those things that probably could be added to slick, but my focus is moreso on making it easy enough to build yourself 😄 , Everyone is probably going to have a slightly different need in this area, so it's nice if it's easily customizable.

That said, I haven't yet packaged it up into a shareable piece, but you can see how I did it for my site here:
https://github.com/ChrisPenner/ChrisPenner.github.io/blob/site/app/Main.hs#L154-L176

If you feel like it you could even implement the combinators as a library 😄

**Comment by ghost** [comment]
Cool thanks! I'll take a look at how you did it and do the same. W.r.t. contributing the result, I'm entirely new to Haskell so I'm afraid I have no idea how to turn it into a generic combinator :D maybe in the future!

**Comment by ChrisPenner** [comment]
No problem! Hope you're having a good experience 😄
