### ISSUE TITLE
feed generation

### ISSUE THREAD

**Issue by timbod7** [ChrisPenner/slick-template#7]
Thanks for slick - I'm migrating content out of an ancient wordpress blog, and it works really well.

Can you share the code you use to generate the rss feed in your personal blog? If it were in this template it would save others having to re-create it.

**Comment by ChrisPenner** [comment]
Yeah, adding it to the template is a good idea, I should do that!

In the mean time you can find the template for the atom feed here: https://github.com/ChrisPenner/ChrisPenner.github.io/blob/site/site/templates/atom.xml

And the setup for your Main.hs is here: https://github.com/ChrisPenner/ChrisPenner.github.io/blob/site/app/Main.hs#L195-L228

Cheers!

**Comment by timbod7** [comment]
That's really helpful. Thank you.
